In [1]:
import reaction_parallel_cython
import numpy as np

In [2]:
N = 20

cellsize = 100

Particle_dtype = np.dtype([
    ('pos', np.float64, (3,)),
    ('vel', np.float64, (3,)),
    ('E', np.float64),
    ('id', np.int32)
], align=True)  # 添加 align=True

Cell_dtype = np.dtype([
    ('id', np.int32),
    ('index', np.int32, (3,)),
    ('film', np.int32, (5,)),
    ('normal', np.float64, (3,))
], align=True)  # 添加 align=True

particle = np.zeros(N, dtype=Particle_dtype)
# cell = np.zeros((cellsize, cellsize, cellsize), dtype=CELLDTYPE)

pos = np.random.rand(N, 3)*99
vel = np.random.rand(N, 3)
energy = np.linalg.norm(vel, axis=1)
vel[:,0] = np.divide(vel[:,0], energy)
vel[:,1] = np.divide(vel[:,1], energy)
vel[:,2] = np.divide(vel[:,2], energy)


# 填充粒子数据
particle['pos'] = pos
particle['vel'] = vel
particle['E'] = 100
particle['id'] = 0
particle[int(N/2):]['id'] = 1
cell = np.zeros((cellsize, cellsize, cellsize), dtype=Cell_dtype)

nn = np.array([0, 0, 1])
# nn = nn/np.linalg.norm(nn)

cell['id'] = 1
cell['index'] = np.array([1,2,3])
cell['film'] = np.array([10,10,10,10,0])
cell['normal'] = nn

cell[:,:,50:]['id'] = 1
print(Particle_dtype.itemsize)
print(Cell_dtype.itemsize)

64
64


In [3]:
particle

array([([57.97574686,  0.19566869, 12.45949719], [0.47016954, 0.27565362, 0.83842453], 100., 0),
       ([17.37345245, 19.25196272, 57.85749803], [0.61279176, 0.09287498, 0.78476779], 100., 0),
       ([ 2.48572019, 33.63060851, 57.70819015], [0.79549285, 0.24017759, 0.5563325 ], 100., 0),
       ([ 5.72594326, 72.18926364, 44.50543032], [0.3950801 , 0.61117485, 0.68584038], 100., 0),
       ([ 1.40577374, 72.6461856 , 38.22223542], [0.73651148, 0.10711341, 0.66789038], 100., 0),
       ([ 3.54652117, 82.77351564, 10.85082737], [0.60833791, 0.63034931, 0.4822704 ], 100., 0),
       ([18.40243368, 23.79905305, 11.09155164], [0.70182771, 0.71161651, 0.03224618], 100., 0),
       ([93.48512487, 32.08776644,  2.5262495 ], [0.61874075, 0.4222035 , 0.66249837], 100., 0),
       ([10.66027302, 87.32588474, 39.96749728], [0.46722806, 0.35100119, 0.81147773], 100., 0),
       ([88.73612209, 36.71994543, 54.22529035], [0.80502491, 0.5338972 , 0.25862846], 100., 0),
       ([45.419237  , 39.62160

In [4]:
a = reaction_parallel_cython.particle_parallel_vector(particle, cell, np.array([cellsize, cellsize, cellsize], dtype=np.double))

In [5]:
np.where(a[0]==-1)



(array([13]),)

In [6]:
particle

array([([58.4459164 ,  0.47132231, 13.29792172], [ 0.47016954,  0.27565362,  0.83842453], 100., 0),
       ([17.98624421, 19.3448377 , 58.64226583], [ 0.61279176,  0.09287498,  0.78476779], 100., 0),
       ([ 3.28121304, 33.87078609, 58.26452265], [ 0.79549285,  0.24017759,  0.5563325 ], 100., 0),
       ([ 6.12102337, 72.80043848, 45.1912707 ], [ 0.3950801 ,  0.61117485,  0.68584038], 100., 0),
       ([ 2.14228522, 72.75329901, 38.8901258 ], [ 0.73651148,  0.10711341,  0.66789038], 100., 0),
       ([ 4.15485908, 83.40386495, 11.33309776], [ 0.60833791,  0.63034931,  0.4822704 ], 100., 0),
       ([19.10426139, 24.51066955, 11.12379782], [ 0.70182771,  0.71161651,  0.03224618], 100., 0),
       ([94.10386562, 32.50996993,  3.18874787], [ 0.61874075,  0.4222035 ,  0.66249837], 100., 0),
       ([11.12750107, 87.67688594, 40.77897501], [ 0.46722806,  0.35100119,  0.81147773], 100., 0),
       ([89.54114699, 37.25384263, 54.48391881], [ 0.80502491,  0.5338972 ,  0.25862846], 100., 0),


In [7]:
# print(a.shape)
print(a[0])
print(a[1])
print(a[2])
print(a[3])

[ 0  0  0  0  0  0  0  0  0  0  3  1  3 -1  2  3  3  3  2  0]
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 1 1 1 0]
 [1 0 1 1 0]
 [0 0 0 0 0]
 [1 0 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 0]
 [0 0 0 1 0]
 [0 0 1 1 0]
 [1 0 1 1 0]]
[[0.79654298 0.         0.         0.         0.        ]
 [0.49686129 0.         0.         0.         0.        ]
 [0.43254171 0.         0.         0.         0.        ]
 [0.30453644 0.         0.         0.         0.        ]
 [0.25804682 0.         0.         0.         0.        ]
 [0.8517575  0.         0.         0.         0.        ]
 [0.42648376 0.         0.         0.         0.        ]
 [0.47373716 0.         0.         0.         0.        ]
 [0.12917458 0.         0.         0.         0.        ]
 [0.32711078 0.         0.         0.         0.        ]
 [0.         0.         0.         0.82337419 0.        ]
 [0.67875499 0.84626541 0.0339859  0.77

In [8]:
print(a[4])

[[-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [ 0  0  0 -1  0]
 [ 0 -1  0  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  0]
 [ 0  0 -1  0  0]
 [-1  0  0  0  0]]


In [9]:
print(a[5])

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [10]:
print(a[6])

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


In [7]:
cell.shape

(100, 100, 100)

In [8]:
added = np.array(np.where(cell['film'][:,:,:,0] != 10)).T

In [9]:
print(added)

[[ 1  9 91]
 [ 5 84 44]
 [26 46 31]
 [27 31 88]
 [42 73 49]
 [45  1 37]
 [47 70 92]
 [61 24 86]
 [84 87 52]
 [92 20 61]
 [93 66  2]
 [95 32  7]]


In [10]:
i = 2
cell[added[i][0],added[i][1],added[i][2]]

(1, [1, 2, 3], [ 9, 11, 10, 10,  0], [0., 0., 1.])

In [14]:
a = reaction_parallel_cython.react_add_test2(particle[0])

print(a)

[0, -1, 1, 0, 0]
[0, -1, 1, 0, 0]


In [ ]:
a = reaction_parallel_cython.react_add_test3(particle)

print(a)

In [3]:
a = reaction_parallel_cython.particle_parallel(particle, cell)

In [ ]:
a.min()

In [ ]:
print(a.shape)
print(a[:200])

In [ ]:
%timeit reaction_parallel_cython.particle_parallel(particle, cell)

In [ ]:
print(a)

In [50]:
@jit(nopython=True, parallel=True)
def particle_parallel_numba(particles, cell):

    dot_product = np.zeros(particles.shape[0], dtype=np.double)

    for i in prange(particles.shape[0]):
        cellijk = particles[i]['pos'].astype(np.int32)

        if cell[cellijk[0],cellijk[1], cellijk[2]]['id'] == 1:
            dot_product[i] = np.dot(particles[i]['vel'], cell[cellijk[0],cellijk[1], cellijk[2]]['normal'])

    return dot_product

In [ ]:
np.arange(0, np.pi/2, 0.01, dtype=np.double).shape

In [ ]:
np.arange(0, np.pi/2, 0.01, dtype=np.double)

In [ ]:
np.linspace(0, np.pi/2, 180, dtype=np.double)

In [ ]:
np.linspace(0, np.pi/2, 180, dtype=np.double).shape

In [38]:

def particle_parallel(particles, cell):

    dot_product = np.zeros(particles.shape[0], dtype=np.double)

    for i in range(particles.shape[0]):
        celli = particles[i]['pos'][0].astype(np.int32)
        cellj = particles[i]['pos'][1].astype(np.int32)
        cellk = particles[i]['pos'][2].astype(np.int32)

        if cell[celli, cellj, cellk]['id'] == 1:
            dot_product[i] = np.dot(particles[i]['vel'], cell[celli, cellj, cellk]['normal'])

    return dot_product

In [ ]:
%timeit particle_parallel_numba(particle, cell)

In [ ]:
%timeit particle_parallel(particle, cell)