In [5]:
import numpy as np


In [12]:
a = np.linspace(0, np.pi/2, 180)

In [13]:
a[-1] == np.pi/2

True

In [1]:
import test_cython

In [3]:
%timeit test_cython.vector_to_numpy_parallel()

4.89 ms ± 555 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit test_cython.vector_to_numpy_parallel_safe()

6.97 ms ± 826 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
x = np.random.rand(40).reshape(8,5)
# x + 0.5
print(x)
x += 0.5
print(x)

[[0.57626753 0.26132122 0.78310279 0.68578148 0.66249812]
 [0.82622163 0.85036619 0.26354621 0.84225926 0.30330076]
 [0.59779592 0.11204846 0.65771672 0.52871992 0.93175938]
 [0.19969619 0.59782156 0.78040615 0.45654055 0.87861657]
 [0.34676142 0.22801483 0.26847335 0.06534214 0.93941123]
 [0.22018475 0.54261151 0.59706843 0.53044733 0.3295923 ]
 [0.29926274 0.19384393 0.28831587 0.75510297 0.36324067]
 [0.52084311 0.96851048 0.03738923 0.19589126 0.31263855]]
[[1.07626753 0.76132122 1.28310279 1.18578148 1.16249812]
 [1.32622163 1.35036619 0.76354621 1.34225926 0.80330076]
 [1.09779592 0.61204846 1.15771672 1.02871992 1.43175938]
 [0.69969619 1.09782156 1.28040615 0.95654055 1.37861657]
 [0.84676142 0.72801483 0.76847335 0.56534214 1.43941123]
 [0.72018475 1.04261151 1.09706843 1.03044733 0.8295923 ]
 [0.79926274 0.69384393 0.78831587 1.25510297 0.86324067]
 [1.02084311 1.46851048 0.53738923 0.69589126 0.81263855]]


In [3]:
x = np.random.rand(40).reshape(8,5)
x += 0.5
print(x)
test_cython.test_pointer(x)

[[0.53671042 1.01486865 1.40110929 0.93207004 0.64422845]
 [1.4323219  1.407855   0.70698113 0.55674246 0.66174338]
 [1.11903074 1.04906169 1.4451318  0.95059148 0.96527261]
 [1.16199743 0.60249601 1.36738404 1.07360873 0.95610597]
 [0.57752278 0.93991583 0.68524322 1.20318809 0.56188319]
 [0.93079384 0.92450727 1.32789336 1.01606864 1.21138662]
 [0.67454701 0.59076055 1.16051104 1.32657354 0.67096413]
 [0.94264805 0.97854255 1.16068693 1.28431227 0.91350873]]


array([0.94264805, 0.        , 0.        , 1.07360873, 0.91350873])

In [3]:
x = np.random.rand(40).reshape(8,5)
x += 0.5
print(x)
test_cython.test_pointer_with_prange(x)

[[0.9149716  1.06895535 0.61170557 1.06464442 0.62925312]
 [0.81076484 1.31642494 0.76158567 0.92604395 1.39473686]
 [1.05388539 1.34427214 0.52504785 0.56649381 0.80907449]
 [0.89629971 1.3514114  0.85733697 0.94752613 0.78757057]
 [1.19034756 0.62398006 0.861558   0.53796403 1.33903313]
 [0.65173696 1.04994111 0.70050178 1.21108117 1.29768684]
 [1.02905212 0.95158954 1.47875178 1.44153635 1.02896252]
 [1.05304266 0.64830676 1.24239932 0.54482912 0.73613664]]


array([0., 0., 2., 0., 4.])

In [7]:
x = np.random.rand(40).reshape(8,5)
x += 0.5
print(x)
test_cython.test_pointer_2(x)

[[1.30175919 1.01431816 0.67394023 1.3148403  1.22819693]
 [0.94441938 0.68138287 0.62392667 0.8889936  1.42481311]
 [1.28980666 0.65342079 0.60160206 0.73096711 0.56413016]
 [0.55867844 0.84832297 0.51176099 1.21970411 0.95328474]
 [0.64416245 1.36892286 1.49433606 0.85655356 0.98802853]
 [0.571585   0.77003112 1.3369921  0.67955457 1.17047113]
 [1.02978686 0.50121289 1.25831602 1.30989078 0.51922911]
 [0.6485913  0.62988259 1.34613401 1.39218098 1.2773086 ]]


array([0.        , 0.        , 1.25831602, 0.        , 0.        ])

In [11]:
x = np.random.rand(40).reshape(8,5)
x += 0.5
print(x)
test_cython.median_along_axis0(x)

[[0.83140912 0.67147711 1.26553957 1.29059239 0.96765684]
 [1.2062586  0.97410154 1.03530711 1.23583016 1.03162872]
 [1.27550937 0.92077147 1.22240575 1.34135361 1.26853085]
 [0.74703282 0.86119617 0.74358794 0.60924495 0.71580979]
 [0.69490845 0.58442674 1.2216111  1.18815023 0.68414986]
 [0.86366543 0.78946367 1.26723125 1.32723281 1.3553802 ]
 [1.16808379 1.05554643 1.08470944 0.77453059 0.71214972]
 [0.53654055 0.93819553 0.58701649 1.373701   0.50306144]]


array([0.86366543, 0.92077147, 1.2216111 , 1.29059239, 0.96765684])

In [3]:
%timeit test_cython.compute(array_1, array_2, a, b, c)

6.23 ms ± 113 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
def compute_np(array_1, array_2, a, b, c):
    return np.clip(array_1, 2, 10) * a + array_2 * b + c

In [5]:
%timeit compute_np(array_1, array_2, a, b, c)

14.8 ms ± 112 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
import sputter_yield
import numpy as np

In [1]:
import react_test
import numpy as np

In [2]:
react_test.test()

[[0.9423 0.9434 2.742  3.026 ]
 [0.962  0.9608 2.542  3.72  ]
 [0.9458 0.9445 2.551  3.735 ]
 [1.046  1.046  2.686  4.301 ]]


In [4]:
a = react_test.example_usage_cimport()

Sputter yield histogram: 0.29330595136327053


In [5]:
print(a)

None


In [7]:
print(sputter_yield.sputterYield_ion)

<MemoryView of 'ndarray' object>


In [9]:
sputter_yield.sputter_yield_coefficient

[0.3, 0.001, 0.7853981633974483]

In [8]:
sp = sputter_yield.sputter_yield(0.5, 0.2, 10, 2)

AttributeError: module 'sputter_yield' has no attribute 'sputter_yield'

In [9]:
sp

0.29330595136327053

In [3]:
import test_cython
import numpy as np

In [2]:
import numpy as np

vel = np.array([5, 6, 7])
vel = vel/np.linalg.norm(vel)


print(vel)

[0.47673129 0.57207755 0.66742381]


In [1]:
import reflection
import numpy as np

In [1]:
import reflection_test
import numpy as np

In [2]:
N = 1

PDTYPE = [('pos', np.float64, (3,)),
          ('vel', np.float64, (3,)),
          ('E', 'f8'), 
          ('id', 'i8')]

CELLDTYPE = [('id', 'i4'), 
            ('index', np.int64, (3,)),
            ('normal', np.float64, (3,)) ]

particle = np.zeros(N, dtype=PDTYPE)
cell = np.zeros(N, dtype=CELLDTYPE)

pos = np.array([1,2,3])
vel = np.array([5, 6, 7])
vel = vel/np.linalg.norm(vel)

nn = np.array([5, 6, 5])
nn = nn/np.linalg.norm(nn)
# 填充粒子数据
particle['pos'] = pos
particle['vel'] = vel
particle['E'] = 100
particle['id'] = 1

cell['id'] = 1
cell['index'] = np.array([1,2,3])
cell['normal'] = nn


In [ ]:
reflection_test.specular(particle[0], cell[0])

In [4]:
reflection_test.DiffusionReflect(particle[0], cell[0])

In [6]:
print(reflection_test.specular(particle[0], cell[0]))

None


In [4]:
def SpecularReflect(vel, normal):
    return vel - 2*vel@normal*normal

In [7]:
def DiffusionReflect(vel, normal):
    Ut = vel - vel@normal*normal
    tw1 = Ut/np.linalg.norm(Ut)
    tw2 = np.cross(tw1, normal)
    # U = np.sqrt(kB*T/particleMass[i])*(np.random.randn()*tw1 + np.random.randn()*tw2 - np.sqrt(-2*np.log((1-np.random.rand())))*normal)
    if np.dot(vel, normal) > 0:
        pm = -1
    else:
        pm = 1
    # print(tw1)
    U = np.random.randn()*tw1 + np.random.randn()*tw2  + pm*np.sqrt(-2*np.log((1-np.random.rand())))*normal
    UN = U / np.linalg.norm(U)
        # UN[i] = U
    return UN

In [8]:
%timeit DiffusionReflect(vel, nn)

32.9 μs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
SpecularReflect(vel, nn)

array([-0.58759904, -0.70511885, -0.39690652])

In [5]:
%timeit reflection_test.DiffusionReflect(particle[0], cell[0])

<magic-timeit>:1: RuntimeWarning: invalid value encountered in sqrt
<magic-timeit>:1: RuntimeWarning: invalid value encountered in log


33.1 μs ± 7.14 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [3]:
%timeit reflection_test.specular(particle[0], cell[0])

6.72 μs ± 14.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:

%timeit SpecularReflect(vel, nn)

3.18 μs ± 7.54 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
N = 1

PDTYPE = [('px', 'f8'), ('py', 'f8'), ('pz', 'f8'),('vx', 'f8'), ('vy', 'f8'), ('vz', 'f8'),('E', 'f8'), ('id', 'i8')]

CELLDTYPE = [('id', 'i4'), 
          ('i', 'i4'), 
          ('j', 'i4'),
          ('k', 'i4'), 
          ('nx', 'f8'), 
          ('ny', 'f8'),
          ('nz', 'f8'), ]

particle = np.zeros(N, dtype=PDTYPE)
cell = np.zeros(N, dtype=CELLDTYPE)

pos = np.array([1,2,3])
vel = np.array([5, 6, 7])
vel = vel/np.linalg.norm(vel)

nn = np.array([-5, -2, 1])
nn = nn/np.linalg.norm(nn)
# 填充粒子数据
particle['px'] = pos[0]
particle['py'] = pos[1]
particle['pz'] = pos[2]
particle['vx'] = vel[0]
particle['vy'] = vel[1]
particle['vz'] = vel[2]
particle['E'] = 100
particle['id'] = 1

cell['id'] = 1
cell['i'] = 1
cell['j'] = 1
cell['k'] = 1
cell['nx'] = nn[0]
cell['ny'] = nn[1]
cell['nz'] = nn[2]

test_cython.compute_particle_angle(particle, cell)

Particle 0, Cell 0, Angle (rad): 1.0213290820372691


In [4]:
N = 5

PDTYPE = [('px', 'f8'), ('py', 'f8'), ('pz', 'f8'),('vx', 'f8'), ('vy', 'f8'), ('vz', 'f8'),('E', 'f8'), ('id', 'i8')]

CELLDTYPE = [('id', 'i4'), 
          ('i', 'i4'), 
          ('j', 'i4'),
          ('k', 'i4'), 
          ('nx', 'f8'), 
          ('ny', 'f8'),
          ('nz', 'f8'), ]

particle = np.zeros(N, dtype=PDTYPE)
cell = np.zeros(N, dtype=CELLDTYPE)

# 填充粒子数据
particle['px'] = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
particle['py'] = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
particle['pz'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particle['vx'] = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
particle['vy'] = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
particle['vz'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particle['E'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particle['id'] = np.array([1, 1, 1, 1, 1])

cell['id'] = np.array([1,1,1,1,1])
cell['i'] = np.array([1,1,1,1,1])
cell['j'] = np.array([1,1,1,1,1])
cell['k'] = np.array([1,1,1,1,1])
cell['nx'] = np.array([1.1, 1.1, 1.1, 1.1, 1.1])
cell['ny'] = np.array([1.2, 1.2, 1.2, 1.2, 1.2])
cell['nz'] = np.array([1.3, 1.3, 1.3, 1.3, 1.3])

# dot = test_cython.test_npdot(particle[1], cell[1])

In [5]:
dot = test_cython.test_npdot(particle[1], cell[1])

7.580000000000001

In [2]:
vel = np.array([1.1, 1.2, 2.2])
theta = np.array([1.1, 1.2, 2.2])

dot = test_cython.test_npdot(vel, theta)

In [3]:
dot

7.49

In [4]:
np.dot(vel, theta)

7.49

In [1]:
import reaction_parallel_cython as test
import numpy as np

In [ ]:
    # int id;
    # int i;
    # int j;
    # int k;
    # double nx;
    # double ny;
    # double nz;

In [2]:
# 创建粒子数据 (N, 4) 数组
N = 1000

FDTYPE = [('id', 'i4'), 
          ('i', 'i4'), 
          ('j', 'i4'),
          ('k', 'i4'), 
          ('nx', 'f8'), 
          ('ny', 'f8'),
          ('nz', 'f8'), ]

film = np.zeros((N, N, N), dtype=FDTYPE)
print(film.itemsize)  # numpy 数组的每个元素大小

film[0, 0, :]['nx'] = np.array([1], dtype=np.int32)

40


In [3]:
print(test.film_test(film))

1000.0


In [6]:
%timeit test.film_test(film)

275 ms ± 43.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
film_np = np.zeros((N, N, N, 7))

film_np[0,0,:, 4] = 1

%timeit np.sum(film_np[:, :, :, 4])

3.23 s ± 399 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
np.sum(film_np[:, :, :, 4])

1000.0

In [6]:
film[0, 0, 0]

(1, 0, 0, 0, 0., 0., 0.)

In [4]:
# 创建粒子数据 (N, 4) 数组
N = 5

DTYPE = [('px', 'f8'), ('py', 'f8'), ('pz', 'f8'),('vx', 'f8'), ('vy', 'f8'), ('vz', 'f8'),('E', 'f8'), ('id', 'i8')]

particles = np.zeros(N, dtype=DTYPE)
print(particles.itemsize)  # numpy 数组的每个元素大小

# 填充粒子数据
particles['px'] = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
particles['py'] = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
particles['pz'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particles['vx'] = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
particles['vy'] = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
particles['vz'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particles['E'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particles['id'] = np.array([1, 1, 1, 1, 1])
film = np.array([10, 10, 10, 10, 10])
angle_rad = 0.3

print(test.sticking_probability_structed(particles[1], film, angle_rad))

64
(array([ True,  True,  True,  True,  True]), 1)


In [6]:
particles[1]

(2., 2.1, 2.2, 2., 2.1, 2.2, 2.2, 1)

In [5]:
%timeit test.sticking_probability_structed(particles[1], film, angle_rad)

25.4 μs ± 69.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
parcel = np.array([2., 2.1, 2.2, 2., 2.1, 2.2, 2.2, 1])
%timeit test.sticking_probability(parcel, film, angle_rad)

21.4 μs ± 50.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
parcel = np.array([2., 2.1, 2.2, 2., 2.1, 2.2, 2.2, 1])
%timeit sticking_probability(parcel, film, angle_rad)

17.3 μs ± 31.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
# 创建粒子数据 (N, 4) 数组
N = 5

DTYPE = [('px', 'f8'), ('py', 'f8'), ('pz', 'f8'),('vx', 'f8'), ('vy', 'f8'), ('vz', 'f8'),('E', 'f8'), ('id', 'i8')]

particles = np.zeros(N, dtype=DTYPE)
print(particles.itemsize)  # numpy 数组的每个元素大小

# 填充粒子数据
particles['px'] = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
particles['py'] = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
particles['pz'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particles['vx'] = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
particles['vy'] = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
particles['vz'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particles['E'] = np.array([1.2, 2.2, 3.2, 4.2, 5.2])
particles['id'] = np.array([101, 102, 103, 104, 105])

# 调用 Cython 函数处理粒子数据
total_x, total_y, total_z = test.process_particles(particles)

# 打印结果
print("Total X:", total_x)
print("Total Y:", total_y)
print("Total Z:", total_z)

64
Total X: 15.0
Total Y: 15.5
Total Z: 16.0


In [8]:
indice = np.ones(5, dtype=np.bool_)
indice[3] = 0

print(indice)

[ True  True  True False  True]


In [9]:
particles

array([(1., 1.1, 1.2, 1., 1.1, 1.2, 1.2, 101),
       (2., 2.1, 2.2, 2., 2.1, 2.2, 2.2, 102),
       (3., 3.1, 3.2, 3., 3.1, 3.2, 3.2, 103),
       (4., 4.1, 4.2, 4., 4.1, 4.2, 4.2, 104),
       (5., 5.1, 5.2, 5., 5.1, 5.2, 5.2, 105)],
      dtype=[('px', '<f8'), ('py', '<f8'), ('pz', '<f8'), ('vx', '<f8'), ('vy', '<f8'), ('vz', '<f8'), ('E', '<f8'), ('id', '<i8')])

In [10]:
particles = particles[indice]

print(particles)

[(1., 1.1, 1.2, 1., 1.1, 1.2, 1.2, 101)
 (2., 2.1, 2.2, 2., 2.1, 2.2, 2.2, 102)
 (3., 3.1, 3.2, 3., 3.1, 3.2, 3.2, 103)
 (5., 5.1, 5.2, 5., 5.1, 5.2, 5.2, 105)]


In [11]:
particles

array([(1., 1.1, 1.2, 1., 1.1, 1.2, 1.2, 101),
       (2., 2.1, 2.2, 2., 2.1, 2.2, 2.2, 102),
       (3., 3.1, 3.2, 3., 3.1, 3.2, 3.2, 103),
       (5., 5.1, 5.2, 5., 5.1, 5.2, 5.2, 105)],
      dtype=[('px', '<f8'), ('py', '<f8'), ('pz', '<f8'), ('vx', '<f8'), ('vy', '<f8'), ('vz', '<f8'), ('E', '<f8'), ('id', '<i8')])

In [5]:
%timeit total_x, total_y, total_z = test.process_particles(particles)

576 ns ± 0.957 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
particles_np =  np.array([[1.0, 2.0, 3.0, 4.0, 5.0],
                       [1.1, 2.1, 3.1, 4.1, 5.1],
                       [1.2, 2.2, 3.2, 4.2, 5.2]])

%timeit  np.sum(particles_np, axis=1)

2.5 μs ± 5.83 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
rn_coeffcients = np.array([[0.9423, 0.9434, 2.742, 3.026], # 100
                 [0.9620, 0.9608, 2.542, 3.720],  # 1000
                 [0.9458, 0.9445, 2.551, 3.735],  # 1050
                 [1.046, 1.046, 2.686, 4.301]] )    # 10000

rn_matrix = np.array([test.Rn_probability(i) for i in rn_coeffcients])

In [8]:
def Rn_coeffcient(c1, c2, c3, c4, alpha):
    return c1 + c2*np.tanh(c3*alpha - c4)

def Rn_probability(c_list = [0.9423, 0.9434, 2.342, 3.026]):
    rn_angle = np.arange(0, np.pi/2, 0.01)
    # xnew = np.array([])
    rn_prob = [Rn_coeffcient(c_list[0], c_list[1], c_list[2], c_list[3], i) for i in rn_angle]
    rn_prob /= rn_prob[-1]
    rn_prob = 1-rn_prob
    return rn_prob

rn_coeffcients = np.array([[0.9423, 0.9434, 2.742, 3.026], # 100
                 [0.9620, 0.9608, 2.542, 3.720],  # 1000
                 [0.9458, 0.9445, 2.551, 3.735],  # 1050
                 [1.046, 1.046, 2.686, 4.301]] )    # 10000

rn_matrix_np = np.array([Rn_probability(i) for i in rn_coeffcients])

In [9]:
rn_coeffcients = np.array([[0.9423, 0.9434, 2.742, 3.026], # 100
                 [0.9620, 0.9608, 2.542, 3.720],  # 1000
                 [0.9458, 0.9445, 2.551, 3.735],  # 1050
                 [1.046, 1.046, 2.686, 4.301]])     # 10000

rn_matrix = np.array([Rn_probability(i) for i in rn_coeffcients])
rn_energy = np.array([100, 1000, 1050, 10000])
rn_angle = np.arange(0, np.pi/2, 0.01)
theta_angle = np.arange(0, np.pi/2, 0.01)
react_prob_chemical = np.array([0.50, 0.50, 0.50, 0.9, 0.0])
react_redepo_sticking = np.array([1.0, 1.0, 1.0, 1.0, 1.0])

def sticking_probability(parcel, film, angle_rad):
    # num_reactions = react_table.shape[1]
    film_layer = film.shape[0]
    choice = np.random.rand(film_layer)
    for c in range(film_layer):
        if film[c] <= 0:
            choice[c] = 1

    particle = int(parcel[-1])
    # particle > 3 for redepo
    if particle >= 2:
        particle = 2

    sticking_acceptList = np.zeros(film_layer, dtype=np.bool_)
    for j in range(film_layer):
        if particle == 1: # ion sputter
            for e in range(rn_energy.shape[0]):
                if parcel[-2] < rn_energy[e]:
                    energy_range = e
            rn_prob = rn_matrix[energy_range]
            sticking_rate = np.interp(angle_rad, rn_angle, rn_prob)

        elif particle == 0: # chemical p0 reaction type
            sticking_rate = react_prob_chemical[j]
        elif particle >= 2:
            sticking_rate = react_redepo_sticking[int(parcel[-1]) - 2]

        if sticking_rate > choice[j]:
            sticking_acceptList[j] = True
    return sticking_acceptList, particle

In [6]:
parcel = np.array([1, 1, 1, 1, 1, 1])
film = np.array([10, 10, 10, 10, 10])
angle_rad = 0.3
%timeit sticking_probability(parcel, film, angle_rad)

16.3 μs ± 41.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
parcel = np.array([1, 1, 1, 1, 1, 1])
film = np.array([10, 10, 10, 10, 10])
angle_rad = 0.3

print(sticking_probability(parcel, film, angle_rad))

(array([ True,  True,  True,  True,  True]), 1)


In [8]:
parcel = np.array([1.1, 1, 1, 1, 1, 1])
film = np.array([10, 10, 10, 10, 10])
angle_rad = 0.3

print(test.sticking_probability(parcel, film, angle_rad))

(array([ True,  True,  True,  True,  True]), 1)


In [7]:
# 创建 numpy 数组 film
film = np.array([1, 0, 3, -1, 5], dtype=np.int32)

# 创建 Parcel 结构体并赋值
my_parcel = {
    'field1': 1.23,
    'field2': 4.56,
    'field3': 7.89,
    'particle_type': 1
}

# 调用 Cython 函数并传递 Parcel 和 numpy 数组
result = test.sticking_probability(my_parcel, film, 0.5)

# 打印结果
print(result)

TypeError: a bytes-like object is required, not 'dict'

In [4]:
angle_rad = 0.3
%timeit test.sticking_probability(my_parcel, film, angle_rad)

20.9 μs ± 76.9 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
parcel = np.array([1.1, 1, 1, 1, 1, 1])
film = np.array([10, 10, 10, 10, 10])
angle_rad = 0.3
%timeit test.sticking_probability(parcel, film, angle_rad)

21 μs ± 88.1 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%timeit np.array([Rn_probability(i) for i in rn_coeffcients])

822 μs ± 2.14 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
print(rn_matrix_np)

[[0.99809747 0.99795514 0.99780484 0.9976461  0.99747846 0.99730144
  0.99711449 0.99691708 0.99670862 0.99648849 0.99625606 0.99601063
  0.99575149 0.99547787 0.99518899 0.99488398 0.99456197 0.99422202
  0.99386314 0.99348429 0.99308438 0.99266224 0.99221667 0.99174639
  0.99125004 0.99072622 0.99017342 0.98959008 0.98897455 0.98832509
  0.98763988 0.986917   0.98615444 0.98535007 0.98450168 0.98360693
  0.98266339 0.98166847 0.9806195  0.97951365 0.97834796 0.97711936
  0.9758246  0.9744603  0.97302292 0.97150878 0.96991401 0.96823461
  0.96646637 0.96460494 0.96264577 0.96058415 0.95841517 0.95613374
  0.95373459 0.95121227 0.94856112 0.94577533 0.94284888 0.93977559
  0.9365491  0.93316288 0.92961025 0.92588437 0.9219783  0.91788492
  0.91359706 0.90910742 0.90440866 0.8994934  0.89435422 0.88898374
  0.8833746  0.87751956 0.87141146 0.86504333 0.85840839 0.85150015
  0.84431239 0.83683926 0.82907535 0.82101571 0.81265594 0.80399222
  0.79502142 0.78574112 0.77614972 0.76624644 0.