In [1]:
import reaction_parallel_cython
import numpy as np

In [2]:
N = 20

cellsize = 100

Particle_dtype = np.dtype([
    ('pos', np.float64, (3,)),
    ('vel', np.float64, (3,)),
    ('E', np.float64),
    ('id', np.int32)
], align=True)  # 添加 align=True

Cell_dtype = np.dtype([
    ('id', np.int32),
    ('index', np.int32, (3,)),
    ('film', np.int32, (5,)),
    ('normal', np.float64, (3,))
], align=True)  # 添加 align=True

particle = np.zeros(N, dtype=Particle_dtype)
# cell = np.zeros((cellsize, cellsize, cellsize), dtype=CELLDTYPE)

pos = np.random.rand(N, 3)*99
vel = np.random.rand(N, 3)
energy = np.linalg.norm(vel, axis=1)
vel[:,0] = np.divide(vel[:,0], energy)
vel[:,1] = np.divide(vel[:,1], energy)
vel[:,2] = np.divide(vel[:,2], energy)


# 填充粒子数据
particle['pos'] = pos
particle['vel'] = vel
particle['E'] = 100
particle['id'] = 0
particle[int(N/2):]['id'] = 1
cell = np.zeros((cellsize, cellsize, cellsize), dtype=Cell_dtype)

nn = np.array([0, 0, 1])
# nn = nn/np.linalg.norm(nn)

cell['id'] = 1
cell['index'] = np.array([1,2,3])
cell['film'] = np.array([10,10,10,10,0])
cell['normal'] = nn

cell[:,:,50:]['id'] = 1
print(Particle_dtype.itemsize)
print(Cell_dtype.itemsize)

64
64


In [3]:
particle

array([([ 3.87235847, 17.75689226,  3.52234007], [0.60504164, 0.44881105, 0.6576422 ], 100., 0),
       ([52.01536258, 59.92890641, 68.37597232], [0.58584717, 0.50798268, 0.63145601], 100., 0),
       ([57.13361589, 20.20833732, 97.22979713], [0.05876292, 0.59257079, 0.80337213], 100., 0),
       ([ 8.19229551, 22.21085194, 44.99216252], [0.6425972 , 0.42757441, 0.63580576], 100., 0),
       ([20.03610253, 62.42141704, 87.18684991], [0.42561359, 0.74646583, 0.51150937], 100., 0),
       ([27.63880066, 77.54318512,  1.2411408 ], [0.56951615, 0.74658214, 0.34389891], 100., 0),
       ([73.95205791, 17.78761084, 20.4399318 ], [0.54096628, 0.1087534 , 0.83398332], 100., 0),
       ([37.43099482, 40.99160742, 31.84839327], [0.18980161, 0.6238375 , 0.75815706], 100., 0),
       ([94.92348349, 83.99571464, 38.80692206], [0.56353806, 0.82382907, 0.06107788], 100., 0),
       ([37.79170204, 72.53486733, 74.38560241], [0.56404267, 0.82219906, 0.07644978], 100., 0),
       ([36.14410081, 37.51907

In [4]:
a = reaction_parallel_cython.particle_parallel_vector(particle, cell, np.array([cellsize, cellsize, cellsize], dtype=np.double))

In [5]:
np.where(a[0]==-1)



(array([14, 17]),)

In [6]:
particle

array([([ 4.47740011, 18.2057033 ,  4.17998227], [ 0.60504164,  0.44881105,  0.6576422 ], 100., 0),
       ([52.60120975, 60.43688909, 69.00742832], [ 0.58584717,  0.50798268,  0.63145601], 100., 0),
       ([57.19237881, 20.80090811, 98.03316925], [ 0.05876292,  0.59257079,  0.80337213], 100., 0),
       ([ 8.83489271, 22.63842636, 45.62796828], [ 0.6425972 ,  0.42757441,  0.63580576], 100., 0),
       ([20.46171612, 63.16788286, 87.69835929], [ 0.42561359,  0.74646583,  0.51150937], 100., 0),
       ([28.20831681, 78.28976726,  1.58503971], [ 0.56951615,  0.74658214,  0.34389891], 100., 0),
       ([74.49302419, 17.89636424, 21.27391512], [ 0.54096628,  0.1087534 ,  0.83398332], 100., 0),
       ([37.62079643, 41.61544492, 32.60655033], [ 0.18980161,  0.6238375 ,  0.75815706], 100., 0),
       ([95.48702155, 84.81954371, 38.86799995], [ 0.56353806,  0.82382907,  0.06107788], 100., 0),
       ([38.35574471, 73.35706639, 74.46205219], [ 0.56404267,  0.82219906,  0.07644978], 100., 0),


In [8]:
np.linalg.norm(np.array([-0.19690162, -0.08145782, -0.97703346]))

1.0000000031786742

In [10]:
np.linalg.norm(np.array([0.60504164, 0.44881105, 0.6576422 ]))

1.000000003978416

In [7]:
# print(a.shape)
print(a[0])
print(a[1])
print(a[2])
print(a[3])

[ 0  0  0  0  0  0  0  0  0  0  1  2  2  1 -1  2  0 -1  2  2]
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 0 0]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 1 0 0]]
[[0.88452079 0.         0.         0.         0.        ]
 [0.79724123 0.         0.         0.         0.        ]
 [0.7898093  0.         0.         0.         0.        ]
 [0.33746254 0.         0.         0.         0.        ]
 [0.6740954  0.         0.         0.         0.        ]
 [0.47123019 0.         0.         0.         0.        ]
 [0.5827221  0.         0.         0.         0.        ]
 [0.43777867 0.         0.         0.         0.        ]
 [0.29238065 0.         0.         0.         0.        ]
 [0.56943119 0.         0.         0.         0.        ]
 [0.26073543 0.66737785 0.39280574 0.         0.        ]
 [0.         0.39113413 0.70304003 0.  

In [8]:
print(a[4])

[[-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  0  0  0  0]
 [ 0 -1  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0 -1  0]
 [ 0 -1  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0  0 -1  0]
 [ 0  0 -1  0  0]
 [-1  0  0  0  0]
 [-1  0  0  0  0]]


In [9]:
print(a[5])

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [10]:
print(a[6])

[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [7]:
cell.shape

(100, 100, 100)

In [8]:
added = np.array(np.where(cell['film'][:,:,:,0] != 10)).T

In [9]:
print(added)

[[ 1  9 91]
 [ 5 84 44]
 [26 46 31]
 [27 31 88]
 [42 73 49]
 [45  1 37]
 [47 70 92]
 [61 24 86]
 [84 87 52]
 [92 20 61]
 [93 66  2]
 [95 32  7]]


In [10]:
i = 2
cell[added[i][0],added[i][1],added[i][2]]

(1, [1, 2, 3], [ 9, 11, 10, 10,  0], [0., 0., 1.])

In [14]:
a = reaction_parallel_cython.react_add_test2(particle[0])

print(a)

[0, -1, 1, 0, 0]
[0, -1, 1, 0, 0]


In [ ]:
a = reaction_parallel_cython.react_add_test3(particle)

print(a)

In [3]:
a = reaction_parallel_cython.particle_parallel(particle, cell)

In [ ]:
a.min()

In [ ]:
print(a.shape)
print(a[:200])

In [ ]:
%timeit reaction_parallel_cython.particle_parallel(particle, cell)

In [ ]:
print(a)

In [50]:
@jit(nopython=True, parallel=True)
def particle_parallel_numba(particles, cell):

    dot_product = np.zeros(particles.shape[0], dtype=np.double)

    for i in prange(particles.shape[0]):
        cellijk = particles[i]['pos'].astype(np.int32)

        if cell[cellijk[0],cellijk[1], cellijk[2]]['id'] == 1:
            dot_product[i] = np.dot(particles[i]['vel'], cell[cellijk[0],cellijk[1], cellijk[2]]['normal'])

    return dot_product

In [ ]:
np.arange(0, np.pi/2, 0.01, dtype=np.double).shape

In [ ]:
np.arange(0, np.pi/2, 0.01, dtype=np.double)

In [ ]:
np.linspace(0, np.pi/2, 180, dtype=np.double)

In [ ]:
np.linspace(0, np.pi/2, 180, dtype=np.double).shape

In [38]:

def particle_parallel(particles, cell):

    dot_product = np.zeros(particles.shape[0], dtype=np.double)

    for i in range(particles.shape[0]):
        celli = particles[i]['pos'][0].astype(np.int32)
        cellj = particles[i]['pos'][1].astype(np.int32)
        cellk = particles[i]['pos'][2].astype(np.int32)

        if cell[celli, cellj, cellk]['id'] == 1:
            dot_product[i] = np.dot(particles[i]['vel'], cell[celli, cellj, cellk]['normal'])

    return dot_product

In [ ]:
%timeit particle_parallel_numba(particle, cell)

In [ ]:
%timeit particle_parallel(particle, cell)