In [1]:
import numpy as np
import react
# from react import ParticleSystem


# 生成10个粒子
particles = react.initial(10)

# 访问第一个粒子的属性
print(f"第一个粒子ID: {particles[0].id}")
print(f"位置: ({particles[0].pos[0]}, {particles[0].pos[1]}, {particles[0].pos[2]})")
print(f"速度: ({particles[0].vel[0]}, {particles[0].vel[1]}, {particles[0].vel[2]})")

第一个粒子ID: 0
位置: (92.34568807990917, 17.69449182415239, 92.73397973957529)
速度: (-0.6926156069276381, 0.7238300387096646, 0.5132621191310787)


In [1]:
from react import double3, ParticleSystem
v = double3(1,2,3)
print(v[0])  # 输出1.0
v[1] = 5.5   # 修改第二个元素


1.0


In [6]:
ps = ParticleSystem(seed=42)

# 生成 1000 个粒子，温度参数 1.0
ps.initialize(1000, 1.0, 10, 40, 100)

# 添加新粒子
new_pos = double3(50.0, 50.0, 50.0)
new_vel = double3(0.1, -0.2, 0.3)
ps.add_particle(new_pos, new_vel, E=0.5, id=44)

# 删除粒子 (假设知道 ID=42)
ps.remove_particle(42)

# 获取所有粒子数据
particles = ps.get_particles()
print(f"当前粒子数量: {len(particles)}")
print("第一个粒子信息:")
print(f"ID: {particles[0].id}")
print(f"位置: {particles[0].pos}")
print(f"速度: {particles[0].vel}")
print(f"能量: {particles[0].E}")

当前粒子数量: 1001
第一个粒子信息:
ID: 40
位置: vec3(79.654298, 18.343479, 77.969100)
速度: vec3(-1.197806, 2.141658, -0.094621)
能量: 10.0


In [7]:
n = 19
print(f"ID: {particles[n].id}")
print(f"位置: {particles[n].pos}")
print(f"速度: {particles[n].vel}")
print(f"能量: {particles[n].E}")

ID: 40
位置: vec3(68.070546, 53.093458, 44.778316)
速度: vec3(2.158729, 1.231778, -0.214324)
能量: 10.0


In [2]:
# 访问第一个粒子的属性
n = 2
print(f"第一个粒子ID: {particles[n].id}")
print(f"位置: ({particles[n].pos[0]}, {particles[n].pos[1]}, {particles[n].pos[2]})")
print(f"速度: ({particles[n].vel[0]}, {particles[n].vel[1]}, {particles[n].vel[2]})")

第一个粒子ID: 2
位置: (53.756882613447765, 41.82333581108318, 76.4750022530834)
速度: (0.8879094019127671, -0.9893520553155045, -0.40873104211704725)


In [1]:
import reaction_parallel_cython
import numpy as np
import film_optimized
# import numpy as np

In [2]:
film = np.zeros((10,10,10), dtype=int)
film[:,:, :5] = 1  # 7x7x7立方体
film[6:,6:, 6] = 1  # 7x7x7立方体
normal_matrix = np.zeros((10,10,10,3), dtype=float)
point = np.array([5,5,5])  # 立方体中心

result = film_optimized.get_normal_from_grid(
    film,
    normal_matrix,
    mirrorGap=0,
    point=point
)

# 预期法向量应为[0,0,1]方向
print(result[5,5,5])  # 应输出接近[0,0,1]

[-0.10114361 -0.10114361  0.9897171 ]


In [8]:
film = np.zeros((10,10,10), dtype=int)
film[:,:, :5] = 1  # 7x7x7立方体
film[6:,6:, 6] = 1  # 7x7x7立方体
normal_matrix = np.zeros((10,10,10,3), dtype=float)
point = np.array([5,4,5])  # 立方体中心

result = film_optimized.get_normal_from_grid(
    film,
    normal_matrix,
    mirrorGap=0,
    point=point
)

# 预期法向量应为[0,0,1]方向
print(result[5,4,5])  # 应输出接近[0,0,1]

[-0.0677534  -0.08516682  0.99406041]


In [2]:
Cell_dtype = np.dtype([
    ('id', np.int32),
    ('index', np.int32, (3,)),
    ('film', np.int32, (5,)),
    ('normal', np.float64, (3,))
], align=True)  # 添加 align=True

cell = np.zeros((10,10,10), dtype=Cell_dtype)
point = np.array([5,4,5])  # 立方体中心
# nn = np.array([0, 0, 1])
# nn = nn/np.linalg.norm(nn)

# cell['id'] = 1
# cell['index'] = np.array([1,2,3])
# cell['film'] = np.array([10,10,10,10,0])
# cell['normal'] = nn

cell[:,:, :5]['id'] = 1
cell[6:,6:, 6]['id'] = 1

film_optimized.get_normal_from_grid_Cell(
    cell,
    point=point
)

In [9]:
Cell_dtype = np.dtype([
    ('id', np.int32),
    ('index', np.int32, (3,)),
    ('film', np.int32, (5,)),
    ('normal', np.float64, (3,))
], align=True)  # 添加 align=True

cell = np.zeros((10,10,10), dtype=Cell_dtype)
point = np.array([[5,4,5],
                  [3,4,5]],dtype=np.int32)  # 立方体中心
# nn = np.array([0, 0, 1])
# nn = nn/np.linalg.norm(nn)

# cell['id'] = 1
# cell['index'] = np.array([1,2,3])
# cell['film'] = np.array([10,10,10,10,0])
# cell['normal'] = nn

cell[:6,:6, 5]['id'] = 1
cell[6:,6:, 6]['id'] = 1

film_optimized.update_normal_in_matrix(
    cell,
    point_to_change=point
)

In [10]:
cell[3,3,5]['id']

1

In [11]:
cell[8,8,6]['id']

1

In [12]:
cell[5,4,5]['id']

1

In [13]:
cell[5,4,5]['normal']

array([-0.12911312, -0.08921984,  0.98760803])

In [14]:
cell[6,:,6]['normal']

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.11951886, -0.11951886,  0.98561173],
       [-0.12468917, -0.11980782,  0.98493588],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [15]:
cell[5,:,5]['normal']

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.        ,  0.        ,  1.        ],
       [-0.11823282, -0.05306785,  0.99156684],
       [-0.12911312, -0.08921984,  0.98760803],
       [-0.11951886, -0.11951886,  0.98561173],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [51]:
np.where(result != 0)

NameError: name 'result' is not defined

In [2]:
film_optimized.print_values(42, 3.14)

C++ 打印的值: a = 42, b = 3.14


In [2]:
N = 20000

cellsize = 100

Particle_dtype = np.dtype([
    ('pos', np.float64, (3,)),
    ('vel', np.float64, (3,)),
    ('E', np.float64),
    ('id', np.int32)
], align=True)  # 添加 align=True

Cell_dtype = np.dtype([
    ('id', np.int32),
    ('index', np.int32, (3,)),
    ('film', np.int32, (5,)),
    ('normal', np.float64, (3,))
], align=True)  # 添加 align=True

particle = np.zeros(N, dtype=Particle_dtype)
# cell = np.zeros((cellsize, cellsize, cellsize), dtype=CELLDTYPE)

pos = np.random.rand(N, 3)*99
vel = np.random.rand(N, 3)
energy = np.linalg.norm(vel, axis=1)
vel[:,0] = np.divide(vel[:,0], energy)
vel[:,1] = np.divide(vel[:,1], energy)
vel[:,2] = np.divide(vel[:,2], energy)


# 填充粒子数据
particle['pos'] = pos
particle['vel'] = vel
particle['E'] = 100
particle['id'] = 0
particle[int(N/2):]['id'] = 1
cell = np.zeros((cellsize, cellsize, cellsize), dtype=Cell_dtype)

nn = np.array([0, 0, 1])
# nn = nn/np.linalg.norm(nn)

cell['id'] = 1
cell['index'] = np.array([1,2,3])
cell['film'] = np.array([10,10,10,10,0])
cell['normal'] = nn

cell[:,:,50:]['id'] = 1
print(Particle_dtype.itemsize)
print(Cell_dtype.itemsize)

64
64


In [4]:
point_etch = np.array([[4,5,6],
                       [5,5,6],
                       [41,5,6],
                       [13,5,6]], dtype=np.int32)
# point_etch = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)  # 示例蚀刻点
cell_size = np.array([10, 10, 10], dtype=np.int32)
# 调用优化后的函数
result = film_optimized.update_film_label_index_normal_etch(
    cell,  # 确保内存连续
    point_etch,
    cell_size
)

print("邻接点坐标矩阵:\n", result)

邻接点坐标矩阵:
 [[[ 5  5  6]
  [ 3  5  6]
  [ 4  6  6]
  [ 4  4  6]
  [ 4  5  7]
  [ 4  5  5]]

 [[ 6  5  6]
  [ 4  5  6]
  [ 5  6  6]
  [ 5  4  6]
  [ 5  5  7]
  [ 5  5  5]]

 [[42  5  6]
  [40  5  6]
  [41  6  6]
  [41  4  6]
  [41  5  7]
  [41  5  5]]

 [[14  5  6]
  [12  5  6]
  [13  6  6]
  [13  4  6]
  [13  5  7]
  [13  5  5]]]


In [8]:
%timeit result = film_optimized.update_film_label_index_normal_etch(cell,  point_etch,cell_size)

2.52 μs ± 5.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
result = film_optimized.update_film_label_index_normal_etch(
    cell,  # 确保内存连续
    point_etch,
    cell_size
)

print("邻接点坐标矩阵:\n", result)

邻接点坐标矩阵:
 [[[ 5  5  6]
  [ 3  5  6]
  [ 4  6  6]
  [ 4  4  6]
  [ 4  5  7]
  [ 4  5  5]]

 [[ 6  5  6]
  [ 4  5  6]
  [ 5  6  6]
  [ 5  4  6]
  [ 5  5  7]
  [ 5  5  5]]

 [[42  5  6]
  [40  5  6]
  [41  6  6]
  [41  4  6]
  [41  5  7]
  [41  5  5]]

 [[14  5  6]
  [12  5  6]
  [13  6  6]
  [13  4  6]
  [13  5  7]
  [13  5  5]]]


In [9]:
%timeit  test = reaction_parallel_cython.update_film_label_index_normal_etch(cell, point_etch, cell_size)

: 

In [3]:
point_etch = np.array([[4,5,6],
                       [5,5,6],
                       [41,5,6],
                       [13,5,6]], dtype=np.int32)

test = reaction_parallel_cython.update_film_label_index_normal_etch(cell, point_etch, np.array([cellsize,cellsize,cellsize],dtype=np.int32))

print(test)

: 

In [5]:
cell[4,5,6]

(0, [1, 2, 3], [10, 10, 10, 10,  0], [0., 0., 1.])

In [6]:
point_etch = np.array([[1,2,3],
                       [4,5,6]], dtype=np.int32)

test = reaction_parallel_cython.update_film_label_index_normal_etch(point_etch)

print(test)

[[[2 2 3]
  [0 2 3]
  [1 3 3]
  [1 1 3]
  [1 2 4]
  [1 2 2]]

 [[5 5 6]
  [3 5 6]
  [4 6 6]
  [4 4 6]
  [4 5 7]
  [4 5 5]]]


In [2]:
import numpy as np
from numba import jit, prange

In [3]:
@jit(nopython=True, parallel=True)
def func(a):
    b = np.ones(a.shape[0], dtype=np.bool_)
    for i in prange(a.shape[0]):
        a[i] += 1
        if a[i] == 10:
            b[i] = False
    a = a[b]
    print(b)
    return a

a = np.arange(20)
print(a)
a =func(a)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ True  True  True  True  True  True  True  True  True False  True  True
  True  True  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 20]


In [2]:
N = 20000

cellsize = 100

Particle_dtype = np.dtype([
    ('pos', np.float64, (3,)),
    ('vel', np.float64, (3,)),
    ('E', np.float64),
    ('id', np.int32)
], align=True)  # 添加 align=True

Cell_dtype = np.dtype([
    ('id', np.int32),
    ('index', np.int32, (3,)),
    ('film', np.int32, (5,)),
    ('normal', np.float64, (3,))
], align=True)  # 添加 align=True

particle = np.zeros(N, dtype=Particle_dtype)
# cell = np.zeros((cellsize, cellsize, cellsize), dtype=CELLDTYPE)

pos = np.random.rand(N, 3)*99
vel = np.random.rand(N, 3)
energy = np.linalg.norm(vel, axis=1)
vel[:,0] = np.divide(vel[:,0], energy)
vel[:,1] = np.divide(vel[:,1], energy)
vel[:,2] = np.divide(vel[:,2], energy)


# 填充粒子数据
particle['pos'] = pos
particle['vel'] = vel
particle['E'] = 100
particle['id'] = 0
particle[int(N/2):]['id'] = 1
cell = np.zeros((cellsize, cellsize, cellsize), dtype=Cell_dtype)

nn = np.array([0, 0, 1])
# nn = nn/np.linalg.norm(nn)

cell['id'] = 1
cell['index'] = np.array([1,2,3])
cell['film'] = np.array([10,10,10,10,0])
cell['normal'] = nn

cell[:,:,50:]['id'] = 1
print(Particle_dtype.itemsize)
print(Cell_dtype.itemsize)

64
64


In [3]:
particle

array([([63.28216417, 19.90604289, 71.1009136 ], [0.59163866, 0.28816463, 0.75294412], 100., 0),
       ([ 7.09057255, 26.24846237, 32.14278464], [0.4544156 , 0.1424588 , 0.87932472], 100., 0),
       ([ 6.24283828, 71.57751135, 20.29343841], [0.22132517, 0.84652945, 0.48415189], 100., 0),
       ...,
       ([14.38213001, 60.6147457 , 52.33644652], [0.5673904 , 0.81797366, 0.09480102], 100., 1),
       ([56.92834095,  0.66256749,  8.51493994], [0.54086223, 0.78271715, 0.30793166], 100., 1),
       ([79.58907139, 37.77174277,  0.6679039 ], [0.78911684, 0.34627667, 0.50733331], 100., 1)],
      dtype={'names': ['pos', 'vel', 'E', 'id'], 'formats': [('<f8', (3,)), ('<f8', (3,)), '<f8', '<i4'], 'offsets': [0, 24, 48, 56], 'itemsize': 64, 'aligned': True})

In [4]:
a = reaction_parallel_cython.particle_parallel_vector_opt(particle, cell, np.array([cellsize, cellsize, cellsize], dtype=np.double))

In [6]:
%timeit -n 100 reaction_parallel_cython.particle_parallel_vector_opt(particle, cell, np.array([cellsize, cellsize, cellsize], dtype=np.double))

6.05 ms ± 252 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
np.where(a[0]==-1)



(array([], dtype=int64),)

In [1]:
particle

NameError: name 'particle' is not defined

In [8]:
np.linalg.norm(np.array([-0.19690162, -0.08145782, -0.97703346]))

1.0000000031786742

In [10]:
np.linalg.norm(np.array([0.60504164, 0.44881105, 0.6576422 ]))

1.000000003978416

In [7]:
# print(a.shape)
print(a[0])
print(a[1])
print(a[2])
print(a[3])

[ 0  0  0  0  0  0  0  0  0  0  1  2  2  1 -1  2  0 -1  2  2]
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 1 1 0 0]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 1 0 0]]
[[0.88452079 0.         0.         0.         0.        ]
 [0.79724123 0.         0.         0.         0.        ]
 [0.7898093  0.         0.         0.         0.        ]
 [0.33746254 0.         0.         0.         0.        ]
 [0.6740954  0.         0.         0.         0.        ]
 [0.47123019 0.         0.         0.         0.        ]
 [0.5827221  0.         0.         0.         0.        ]
 [0.43777867 0.         0.         0.         0.        ]
 [0.29238065 0.         0.         0.         0.        ]
 [0.56943119 0.         0.         0.         0.        ]
 [0.26073543 0.66737785 0.39280574 0.         0.        ]
 [0.         0.39113413 0.70304003 0.  

In [8]:
print(a[4])

[[-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  1  0  0  0]
 [-1  0  0  0  0]
 [ 0 -1  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0 -1  0]
 [ 0 -1  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0  0 -1  0]
 [ 0  0 -1  0  0]
 [-1  0  0  0  0]
 [-1  0  0  0  0]]


In [9]:
print(a[5])

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [10]:
print(a[6])

[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [7]:
cell.shape

(100, 100, 100)

In [8]:
added = np.array(np.where(cell['film'][:,:,:,0] != 10)).T

In [9]:
print(added)

[[ 1  9 91]
 [ 5 84 44]
 [26 46 31]
 [27 31 88]
 [42 73 49]
 [45  1 37]
 [47 70 92]
 [61 24 86]
 [84 87 52]
 [92 20 61]
 [93 66  2]
 [95 32  7]]


In [10]:
i = 2
cell[added[i][0],added[i][1],added[i][2]]

(1, [1, 2, 3], [ 9, 11, 10, 10,  0], [0., 0., 1.])

In [14]:
a = reaction_parallel_cython.react_add_test2(particle[0])

print(a)

[0, -1, 1, 0, 0]
[0, -1, 1, 0, 0]


In [ ]:
a = reaction_parallel_cython.react_add_test3(particle)

print(a)

In [3]:
a = reaction_parallel_cython.particle_parallel(particle, cell)

In [ ]:
a.min()

In [ ]:
print(a.shape)
print(a[:200])

In [ ]:
%timeit reaction_parallel_cython.particle_parallel(particle, cell)

In [ ]:
print(a)

In [50]:
@jit(nopython=True, parallel=True)
def particle_parallel_numba(particles, cell):

    dot_product = np.zeros(particles.shape[0], dtype=np.double)

    for i in prange(particles.shape[0]):
        cellijk = particles[i]['pos'].astype(np.int32)

        if cell[cellijk[0],cellijk[1], cellijk[2]]['id'] == 1:
            dot_product[i] = np.dot(particles[i]['vel'], cell[cellijk[0],cellijk[1], cellijk[2]]['normal'])

    return dot_product

In [ ]:
np.arange(0, np.pi/2, 0.01, dtype=np.double).shape

In [ ]:
np.arange(0, np.pi/2, 0.01, dtype=np.double)

In [ ]:
np.linspace(0, np.pi/2, 180, dtype=np.double)

In [ ]:
np.linspace(0, np.pi/2, 180, dtype=np.double).shape

In [38]:

def particle_parallel(particles, cell):

    dot_product = np.zeros(particles.shape[0], dtype=np.double)

    for i in range(particles.shape[0]):
        celli = particles[i]['pos'][0].astype(np.int32)
        cellj = particles[i]['pos'][1].astype(np.int32)
        cellk = particles[i]['pos'][2].astype(np.int32)

        if cell[celli, cellj, cellk]['id'] == 1:
            dot_product[i] = np.dot(particles[i]['vel'], cell[celli, cellj, cellk]['normal'])

    return dot_product

In [ ]:
%timeit particle_parallel_numba(particle, cell)

In [ ]:
%timeit particle_parallel(particle, cell)